### PR TITLE
Added VCNT-8 21.4.0439-MR2.1-RA firmware

### PR DESCRIPTION
**Pull request by seud0nym**

### CODE REVIEW

**Comment by seud0nym** [comment]
Is there a problem with request?

**Comment by LuKePicci** [comment]
Nope, just got beach time 😎

**Comment by seud0nym** [comment]
Lucky you. Thanks for merging those.

It's been a while since stable was updated - will you be doing that soon?

**Comment by LuKePicci** [comment]
Yup, will do on Sunday from my workstation

**Comment by seud0nym** [comment]
Thanks. Will you be merging #300 as well?

**Comment by LuKePicci** [comment]
Holydays gone, PR merged and stable branch updated.

**Pull request merged**
