### PR TITLE
Add tch-gui-unhide GUI modification

### PR DESCRIPTION
**Pull request by seud0nym**
Adds tch-gui-unhide as an alternative to tch-nginx-gui for GUI.

### CODE REVIEW

**Comment by LuKePicci** [comment]
Looks good, but I'd move the last line about other scripts out of the custom gui section. IMHO both ad guard and easymesh stuff deserve their own section, especially if they are not bound to the un hide mod.

**Comment by seud0nym** [comment]
Thanks for the feedback. I have split the scripts into separate sections and expanded it a bit.

**Comment by LuKePicci** [comment]
Ok, we need to describe a little bit further the adguard section with a brief explanation of what the technical result will be. Take the "What it does" from your readme adding some little details on where it would store the database (no need to explain here pros/cons of each option), how much resources it would take (ROM & RAM) and what deployment layouts the scripts supports (replace dnsmasq entirely for DNS and DHCP, only DHCP, chain dnsmasq DNS to agh, etc..)

For the easymesh, I'd like to include some extra details on what is an easymesh agent and how we can check if our technicolor firmware/wifi driver can run/already includes it, what is an easymech controller and how we can check if our technicolor firmware can run it, what it means wired backhauling in easymesh and why it can't/how it could be wireless backhaul.

To better understand my above requests, it is important for this wiki to collect knowledge rather then being a tools' index. In this cases, it is important to describe what these firmwares allows and what limitations they place to somebody else willing to play with agh or easymesh on these devices and maybe guide them in buying the best one for the purpose. it is then up to a modder, like you when you started, to transform this knolwedge into tools and howtos, Now I'd like you to do the opposite, i.e. sharing a bit of knowledge behind your tools while linking to them as PoCs of your experiments.

**Comment by seud0nym** [comment]
I understand perfectly. It is much better to have more information. I hope the latest changes are more in line with what you are after.

**Comment by LuKePicci** [comment]
Thanks a lot, much appreciated.

About, wireless backhauling, @lorenzocanalelc did some experiments with 5GHz radio in STA mode, give a look and see if you find it interesting.

**Comment by seud0nym** [comment]
Thanks.

> About, wireless backhauling, @lorenzocanalelc did some experiments with 5GHz radio in STA mode, give a look and see if you find it interesting.

I could only find some stuff related to Quantenna, which I don't think is relevant to the Telstra devices. Could you give me a link?

**Pull request merged**
