### PR TITLE
Add row to VANT-2 table for firmware 16.2.7064 with timestamp 2017-02-07

### PR DESCRIPTION
**Pull request by StrayLightning**

### CODE REVIEW

**Comment by LuKePicci** [comment]
Thank you again. Your bank dump is now merged on the linked repo. This PR is fine, I'll add the link to the dump and merge if you give me write access to this PR (otherwise I'll do the same in a separate commit).

**Comment by StrayLightning** [comment]
@LuKePicci I added write access for you for my fork of the repo, but I'm not sure if that's enough to give you write access to the PR?

**Comment by LuKePicci** [comment]
I'll try asap and I guess it's enough, but AFAIK there should be an option in the PR to allow writes in there without full write access.

**Comment by LuKePicci** [comment]
Link added, write access worked. I've got into troubles umpacking the bank dump, for some reason the squashfs is said to be corrupted and gives no content. Is that from a dd of the firmware bank or did you dump it another way?

**Comment by StrayLightning** [comment]
Ah, that's a good point: Apologies.  I think that was the second raw flash dump direct from the NAND, which contained one block with errors.  I'll see if I can dig out the corrected dump after ECC, and if not I'll remind myself how to run the error correction.  Expect a new PR soon.

**Comment by LuKePicci** [comment]
Alright, just update the raw dump on that other repo when you finished. I'll keep this on hold.

**Pull request merged**
