### PR TITLE
Added VBNT-V/VCNT-A 20.3.c.0329-MR19-RB

### PR DESCRIPTION
**Pull request by seud0nym**
As per issue #180

### CODE REVIEW

**Comment by LuKePicci** [comment]
Thanks, we only need to add torrents and we are good to go. Create a torrent for each RBI, set the Telstra URL as a web seed for the torrent while you create it. Torrent file must be named the same as the RBI (*. rbi.torrent) and uploaded into torrents folder of this repo. You don't need to keep it seeded as you used Telstra URLs as seeds.

**Comment by seud0nym** [comment]
I don't know how to do that.

**Comment by seud0nym** [comment]
Torrents added. I used an Online Torrent Creator because I am not a torrent user.

**Comment by LuKePicci** [comment]
sry for the delay, l had to check torrents first, Iooks good thanks

**Pull request merged**
